### ISSUE TITLE
出现问题， No key found in 4 PIDs tried.

### ISSUE THREAD

**Issue by caldo0525** [fireattack/extract_kindle#1]
以前下的书依然可以解，但是今天下的书会出现 No key found in 4 PIDs tried.
不知道大佬有没有解决办法 非常感谢！

D:\extract_kindle>python extract_kindle.py "C:/Users/Documents/My Kindle Content/B0DGQ76BV7_EBOK"
Using Library AlfCrypto DLL/DYLIB/SO
Loaded config from config.json.
Folder: C:\Users\Documents\My Kindle Content\B0DGQ76BV7_EBOK
DeDRMing B0DGQ76BV7_EBOK.azw..
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: BRUTUS(ブルータス) 2024年 10月15日号 No.1017 [猫になりたい。] [雑誌]
Got DSN key from database D:\extract_kindle\kindlekey1.k4i
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
Error decrypting book after 0.1 seconds: No key found in 4 PIDs tried.
Traceback (most recent call last):
  File "D:\extract_kindle\DeDRM_plugin\k4mobidedrm.py", line 258, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\extract_kindle\DeDRM_plugin\k4mobidedrm.py", line 232, in GetDecryptedBook
    mb.processBook(totalpids)
  File "D:\extract_kindle\DeDRM_plugin\mobidedrm.py", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
Traceback (most recent call last):
  File "D:\extract_kindle\extract_kindle.py", line 156, in <module>
    main(*args)
  File "D:\extract_kindle\extract_kindle.py", line 77, in main
    deDRMed_azw_file = next(f for f in p.iterdir() if f.name.endswith('_nodrm.azw3'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

**Comment by fireattack** [comment]
可能是被 amazon 强制升级到了最新版的 kindle，检查一下安装的kindle版本。
另外贴一下 C:/Users/Documents/My Kindle Content/B0DGQ76BV7_EBOK 里面的内容

目前脚本只支持1.39~1.4x版本。

2.4.x的版本的解密虽然我已经搞完了（ https://github.com/fireattack/DeDRM_tools ，还没整合进来），但是因为2.x版本下载的KFX格式图像质量大幅劣化，我没有去更新的欲望

先卸载kindle，删掉此书，然后去 https://www.filepuma.com/download/kindle_for_pc_1.39.65383-33804/ 下载安装这个1.39版。然后启动后测试下能不能正常下载这本书。

启动后先别急着关闭，检查 C:\Users\{用户名}\AppData\Local\Amazon\Kindle\updates\ 检查是否有 KindleForPC-installer.exe 文件，如果有删除，并且建立一个空文件夹改名为KindleForPC-installer.exe 防止 Kindle 自动更新到 2.x版本。

**Comment by caldo0525** [comment]
> 可能是被 amazon 强制升级到了最新版的 kindle，检查一下安装的kindle版本。 另外贴一下 C:/Users/Documents/My Kindle Content/B0DGQ76BV7_EBOK 里面的内容
> 
> 目前脚本只支持1.39~1.4x版本。
> 
> 2.4.x的版本的解密虽然我已经搞完了（ https://github.com/fireattack/DeDRM_tools ，还没整合进来），但是因为2.x版本下载的KFX格式图像质量大幅劣化，我没有去更新的欲望
> 
> 先卸载kindle，删掉此书，然后去 https://www.filepuma.com/download/kindle_for_pc_1.39.65383-33804/ 下载安装这个1.39版。然后启动后测试下能不能正常下载这本书。
> 
> 启动后先别急着关闭，检查 C:\Users{用户名}\AppData\Local\Amazon\Kindle\updates\ 检查是否有 KindleForPC-installer.exe 文件，如果有删除，并且建立一个空文件夹改名为KindleForPC-installer.exe 防止 Kindle 自动更新到 2.x版本。

我的版本是2.01，没有被强制更新，原来是不支持的吗我一直这么用来着。。。
我重新下载了您所说的1.39.2，然后重新试了几本，还是出现一样的问题
![20241030165719](https://github.com/user-attachments/assets/763bee91-f7b8-4121-9873-00d03885f01b)

**Comment by fireattack** [comment]
![image](https://github.com/user-attachments/assets/a1bcb7c0-3b7a-48dc-8588-f74643396191)

我这里我这里一切正常，要么你把 kindlekey1.k4i 文件删除再重试一次？

**Comment by fireattack** [comment]
贴一下你的版本号截图也:

![image](https://github.com/user-attachments/assets/f7918be2-be13-43b0-ae2b-39a6452178f5)

**Comment by caldo0525** [comment]
> 贴一下你的版本号截图也:
> 
> ![image](https://private-user-images.githubusercontent.com/4130991/381504504-f7918be2-be13-43b0-ae2b-39a6452178f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODQ4MzMsIm5iZiI6MTczMDI4NDUzMywicGF0aCI6Ii80MTMwOTkxLzM4MTUwNDUwNC1mNzkxOGJlMi1iZTEzLTQzYjAtYWUyYi0zOWE2NDUyMTc4ZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTAzNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzhjNDVlN2I1OGY3ZmJhMGVjNGFlY2NhMDRiYzU5MjQwNmFlYjI3ODhjZmU0MmQ2OTZhMGRkOTM3ZTRlYTYxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qHrmWkmveCfVsqh-pfQemqh4sQuhOjAEJ8p-ZW9koTQ)

啊删掉kindlekey1.k4i文件就可以了！谢谢！
![20241030190446](https://github.com/user-attachments/assets/a6944794-16ce-4278-a05a-aa65bf446b18)
